name: CI

on: [pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        driver: [Chrome, Firefox]
        base_url:
          - https://www.chateau-staging.com
          - https://www.chateauapp.co
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: python -m pip install --upgrade pip poetry
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run pytest --driver ${{ matrix.driver }} --base-url ${{ matrix.base_url }}
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
